CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY,
    users_id VARCHAR(100) NOT NULL,
    body VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE posts 
ADD CONSTRAINT fk_posts_users 
FOREIGN KEY (users_id) 
REFERENCES users(id) 
ON DELETE CASCADE 
ON UPDATE CASCADE;